print('Пожалуйста, укажите этапы развития человека:')
print('1 этап')
a = input()
print('2 этап')
b = input()
print('3 этап')
c = input()
print('4 этап')
d = input()
print('5 этап')
e = input()
print(a, b, c, d, e, sep="=>")
print()
print("Правильный ответ")
print("Homo habilis", "Homo erectus", "Homo heidelbergensis","Homo neanderthalensis", "Homo sapiens", sep="=>")